{% include 'Dockerfile.header' %}
# install helper scripts
COPY root /
COPY root_server /
{%- if install_agent %}
COPY root_agent/ /
{%- endif %}
# do initial setup
RUN ambari-server setup -s
{% include 'Dockerfile.footer' %}